### PR TITLE
Filter RemovedComponents for entities that no longer exist

### LINKED ISSUE #509: 0.12 bug: despawn + spawn during state change, without spawning texture, panics
Minimal Repro Repo: https://github.com/MeoMix/bevy_bug_example

Relevant Code:

```rust
use bevy::prelude::*;
use bevy_ecs_tilemap::{TilemapPlugin, TilemapBundle};

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, TilemapPlugin))
        .add_state::<ExampleState>()
        .add_systems(Startup, (spawn_camera, spawn_tilemap_example))
        .add_systems(OnExit(ExampleState::State1), despawn_tilemap_example)
        .add_systems(OnEnter(ExampleState::State2), spawn_sprite_example)
        .add_systems(Update, change_example_state)
        .run();
}

#[derive(States, Default, Hash, Clone, Copy, Eq, PartialEq, Debug)]
pub enum ExampleState {
    #[default]
    State1,
    State2,
}

#[derive(Component)]
pub struct ExampleTilemap;

pub fn spawn_camera(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

pub fn spawn_tilemap_example(mut commands: Commands) {
    info!("spawn_tilemap_example");
    commands.spawn((
        ExampleTilemap,
        TilemapBundle {
            ..default()
        },
    ));
}

pub fn despawn_tilemap_example(query: Query<Entity, With<ExampleTilemap>>, mut commands: Commands) {
    info!("despawn_tilemap_example");
    commands.entity(query.single()).despawn();
}

// TODO: Determine why this panics after despawning `TilemapBundle` components
pub fn spawn_sprite_example(mut commands: Commands) {
    info!("spawn_sprite_example");
    commands.spawn(SpriteBundle {
        ..default()
    });
}

pub fn change_example_state(state: Res<State<ExampleState>>, mut next_state: ResMut<NextState<ExampleState>>) {
    if state.get() == &ExampleState::State1 {
        info!("changing state");
        next_state.set(ExampleState::State2);
    }
}
```

This code causes app to panic when using the main branch of bevy_ecs_tilemap + bevy 0.12

This code does not cause app to panic when targeting bevy 0.11.3 and bevy_ecs_tilemap 0.11.0

This code does not panic if `SpriteBundle` is spawned with a texture.

panic occurs here in bevy_render:

```rust
let receiver = world.get_resource::<RenderToMainAppReceiver>().unwrap();
receiver.0.recv().await.unwrap()
```

attempting to unwrap `recv().await.unwrap()` fails

### PR DESCRIPTION
**Pull request by thebluefish**
Fixes #509 

Here is an MVCE demonstrating a crash:
```rust
use bevy::prelude::*;
use bevy_ecs_tilemap::prelude::*;

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, TilemapPlugin))
        .add_state::<ExampleState>()
        .add_systems(Startup, setup)
        .add_systems(Update, transition.run_if(in_state(ExampleState::State1)))
        .add_systems(OnExit(ExampleState::State1), despawn)
        .add_systems(OnEnter(ExampleState::State2), spawn)
        .run();
}

#[derive(Debug, Clone, Copy, Default, Eq, PartialEq, Hash, States)]
enum ExampleState {
    #[default]
    State1,
    State2,
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(TilemapBundle::default());
}

fn transition(mut next_state: ResMut<NextState<ExampleState>>) {
    println!("transitioning");
    next_state.set(ExampleState::State2);
}

fn despawn(mut commands: Commands, query: Query<Entity, With<TileStorage>>) {
    for entity in &query {
        println!("despawning {entity:?}");
        commands.entity(entity).despawn();
    }
}

fn spawn(mut commands: Commands) {
    let entity = commands.spawn_empty().id();
    println!("spawning {entity:?}");
    commands.entity(entity).insert(SpriteBundle::default());
}
```

> transitioning
despawning 2v0
spawning 2v1
2024-02-02T18:54:12.858004Z ERROR bevy_ecs::system::commands: Failed to 'insert or spawn' bundle of type bevy_sprite::render::SpriteBatch into the following invalid entities: [2v1]
thread '<unnamed>' panicked at C:\Users\s33n\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.12.1\src\render_phase\draw.rs:275:67:
called `Result::unwrap()` on an `Err` value: NoSuchEntity(2v1)

I believe the root problem is that we are erroneously inserting an Entity `2v0` into the render world via `ExtractedRemovedMapBundle` when that entity in our current world is now `2v1`. This appears to interfere with systems that interact with that entity in the render world.

### CODE REVIEW

**Comment by thebluefish** [comment]
Digging into this, it seemed that my original fix was a band-aid solution that failed to understand what was being accomplished. It resolved the original problem, but simply by breaking the logic. The new solution fixes what appears to be an inconsistency when extracting, by keeping the same `Entity` between main and render worlds for these temp cleanup components.

**Comment by rparrett** [comment]
Have been following. This new fix makes much more sense to me too.

**Comment by rparrett** [comment]
CI is failing on fmt and clippy.

**Comment by StarArawn** [comment]
@thebluefish Can you run fmt/clippy? If not I'll branch off of your code and open a new PR. :+1: We're planning on rolling out a release tomorrow.

**Comment by thebluefish** [comment]
Ah apologies, I did not see a notification for the prior messages. Should be good now, but I'm not sure how to restart the CI.

**Review by rparrett — APPROVED** [review]
Looks good to me.

**Pull request merged**
