### PR TITLE
Tile maps with an even number of tiles need a half-tile offset applied.

### LINKED ISSUE #342: get_tilemap_center_transform is broken for some tilemaps
### Version tested

Latest commit, 0.9.0

### Problem

Tiles appear to be half a tile too far left and down.

image

### Repro

For dramatic effect, modify `basic.rs` with
```rust
WindowDescriptor {
    width: 540.0,
    height: 540.0,
    /* ... */
}
```
Or just resize the window at runtime.

`cargo run --example basic`

### PR DESCRIPTION
**Pull request by bzm3r**
Fixes #342

### CODE REVIEW

**Comment by rparrett** [comment]
I am not sure if this is working properly for hex and iso maps.

image
image

**Comment by bzm3r** [comment]
@rparrett I just pushed a commit that now calculates the "center" based on the corner points of the central-ish tile. Can you give it a whirl for hexagonal/isometric tiles, and let me know how it looks now?

If it looks good, great. If not then, this is getting finicky enough that it's not a great use of time to solve it...so maybe we just say "eh, that's to be expected for these non-regular tile types?". 

As part of this commit, I have included updates to the helpers which calculate corner positions. So, maybe for more specific cases, users can take advantage of that to figure out how they want to center their tiles? Not sure.

**Comment by rparrett** [comment]
I am not personally invested in hex / iso maps and this does seem like quite a lot to me.

I tried an approach like this and it seems to work well enough with hex/rect tilemaps with odd and even tile counts.

```rust
/// Calculates a [`Transform`] for a tilemap that places it so that the center tile is at
/// `(0.0, 0.0, 0.0)` in world space.
pub fn get_tilemap_center_transform(
    size: &TilemapSize,
    grid_size: &TilemapGridSize,
    map_type: &TilemapType,
    z: f32,
) -> Transform {
    let low = TilePos::new(0, 0).center_in_world(grid_size, map_type);
    let high = TilePos::new(size.x - 1, size.y - 1).center_in_world(grid_size, map_type);

    let diff = high - low;

    Transform::from_xyz(-diff.x / 2., -diff.y / 2., z)
}
```

Maybe it doesn't work with iso. I'm not immediately sure how to modify that example to test and I'm out of time for now.

**Comment by bzm3r** [comment]
@rparrett Yeah, that seems way better, to be honest. I'm facepalming, not sure why I got distracted with calculating corner positions.

**Comment by rparrett** [comment]
The new `get_tilemap_center_transform` worked well for me when I tested it in the absence of the rest of the changes to `center_world_in_pos`, etc.

But in the current changeset, hexagon centering seems broken again.

There are also some unrelated changes in the changeset that snuck in like a (bug fix?) in `filling.rs` and changes to examples.

**Comment by bzm3r** [comment]
@rparrett Yeah, I am fine with putting those in as part of the current change set, as I didn't know how to separate it out, and they were small enough that I would forget them otherwise.

**Pull request closed without merging**
