### PR TITLE
Update to Bevy 0.8

### PR DESCRIPTION
**Pull request by NeoRaider**
This updates all Rust and shader code to work with Bevy 0.8. All examples seem to work fine on my system (Linux Wayland, tested with `--features bevy/wayland` because of https://github.com/bevyengine/bevy/issues/5524).

### CODE REVIEW

**Comment by StarArawn** [comment]
What platform did you test this on? I'm fairly certain it wont work on vulkan due to a WGPU bug.

**Comment by NeoRaider** [comment]
> What platform did you test this on? I'm fairly certain it wont work on vulkan due to a WGPU bug.

Interesting, do you have a link to a bug report?

It seems to work on my machine with Vulkan (as mentioned, I'm on Linux/Wayland):
```
AdapterInfo { name: "AMD RADV RENOIR", vendor: 4098, device: 5686, device_type: IntegratedGpu, backend: Vulkan }
```

**Comment by StarArawn** [comment]
> > What platform did you test this on? I'm fairly certain it wont work on vulkan due to a WGPU bug.
> 
> Interesting, do you have a link to a bug report?
> 
> It seems to work on my machine with Vulkan (as mentioned, I'm on Linux/Wayland):
> 
> ```
> AdapterInfo { name: "AMD RADV RENOIR", vendor: 4098, device: 5686, device_type: IntegratedGpu, backend: Vulkan }
> ```

Huh, it might be a windows only thing. Here is the issue I uncovered:
https://github.com/gfx-rs/naga/issues/2018

I tested this branch specifically and it does not work for me in windows 11, vulkan, and geforce driver 511.79. Dx12 works however.

**Comment by mbolt35** [comment]
Tested this on Windows 10 with Vulkan backend:
```
AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7956, device_type: DiscreteGpu, backend: Vulkan }
```

Works great, no issues so far.

**Comment by StarArawn** [comment]
> Tested this on Windows 10 with Vulkan backend:
> 
> ```
> AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7956, device_type: DiscreteGpu, backend: Vulkan }
> ```
> 
> Works great, no issues so far.

Yeah, I discovered the issue was due to a driver bug. Updating my drivers resolved the issue. I likely still wont merge this as we are fairly close to merging the rewrite branch into master and releasing a new version.

**Comment by mbolt35** [comment]
> Yeah, I discovered the issue was due to a driver bug. Updating my drivers resolved the issue. I likely still wont merge this as we are fairly close to merging the rewrite branch into master and releasing a new version.

Awesome! Looking forward to the changes in rewrite. Just to confirm, the rewrite branch has support for bevy 0.8?

**Comment by StarArawn** [comment]
> Awesome! Looking forward to the changes in rewrite. Just to confirm, the rewrite branch has support for bevy 0.8? 

Correct! Most of the work is done for the rewrite. I'm mostly working on cleaning up docs.

**Pull request closed without merging**
