### PR TITLE
Isometric tilemap height correction

### PR DESCRIPTION
**Pull request by ekaats**
I've made some changes to the isometric rendering to allow for tiles that are not flat to be rendered correctly. In the example I've added some random foliage to show the effect. Still need to figure out the tilemap coordination system, so I was not able to create nice hill/mountain ranges with the correct tiles connecting to each other.

I'm still very new to rust so it is very likely that my approach is not the best.

### CODE REVIEW

**Comment by ekaats** [comment]
This closes #23

**Comment by StarArawn** [comment]
I've been thinking about this for a while, and I'm not yet convinced this is the correct approach.. The iso tilemap size for the ground here is "suppose" to be 64x32, I think for the the "walls" however it might make more sense to have 64x64 tiles. 🤔

**Comment by ekaats** [comment]
That is a fair point. I do wonder whether they actually use different sizes for floor and wall tiles in that tutorial though.  I quickly read through it and it appears they use the same but point out you'd need to draw different tiles compared to the top-down perspective. For example, they say the following: "(Here, we essentially assume that tile height and tile width are equal, as in most cases.) "

The nice thing about loading the tiles as the same height is that you do not need to worry about the difference between the two types of tiles:
bevy_height

Only bigger sprites would need to be handled differently.

**Comment by StarArawn** [comment]
I was looking at how some other isometric 2D games handle rendering and I think I want to rethink and maybe provide some higher level support for iso. Typically draw order is very important as you want to have "walls" potentially draw on-top of sprites. I think we need some mechanisms for translating a 2D point to a 3D point for iso. Also we should likely render each layer from the top down in "sections" at least for diamond. I'm not sure how you would even do that with my current implementation.

**Pull request closed without merging**
